"""Tests for sigmond.coordination loader and env rendering."""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'lib'))

from sigmond.coordination import (
    Coordination, TimingAuthority, load_coordination, parse_coordination,
    render_env, _env_key,
)


SAMPLE_TOML = """\
[host]
call = "AI6VN"
grid = "CM88mc"
lat  = 37.5
lon  = -122.25

[radiod."k3lr-rx888"]
host        = "localhost"
status_dns  = "k3lr-rx888-status.local"
samprate_hz = 64800000
cores       = "0-1"
radio_conf  = "/etc/radio/radiod@k3lr-rx888.conf"

[radiod."shack-airspy"]
host        = "shack.local"
status_dns  = "airspy-status.local"
samprate_hz = 10000000

[cpu]
suite_cores           = "0-11"
worker_cores          = "2-11"
owns_timestd_affinity = true

[[clients.hf-timestd]]
instance         = "rx888-a"
radiod_id        = "k3lr-rx888"
timing_authority = "rtp"

[[clients.hf-timestd]]
instance         = "airspy-b"
radiod_id        = "shack-airspy"
timing_authority = "auto"

[[clients.ka9q-web]]
instance  = "k3lr-rx888"
radiod_id = "k3lr-rx888"
port      = 8081

[disk_budget]
root_path    = "/var"
warn_percent = 80
"""


class TestLoadCoordination(unittest.TestCase):

    def test_empty_when_missing_file(self):
        path = Path('/tmp/does-not-exist-sigmond-coord.toml')
        if path.exists():
            path.unlink()
        coord = load_coordination(path)
        self.assertEqual(coord.host.call, "")
        self.assertEqual(coord.radiods, {})
        self.assertEqual(coord.clients, [])

    def test_parse_full_sample(self):
        import tomllib
        raw = tomllib.loads(SAMPLE_TOML)
        coord = parse_coordination(raw)

        self.assertEqual(coord.host.call, "AI6VN")
        self.assertEqual(coord.host.grid, "CM88mc")
        self.assertAlmostEqual(coord.host.lat, 37.5)

        self.assertIn("k3lr-rx888", coord.radiods)
        self.assertIn("shack-airspy", coord.radiods)
        self.assertTrue(coord.radiods["k3lr-rx888"].is_local)
        self.assertFalse(coord.radiods["shack-airspy"].is_local)
        self.assertEqual(coord.radiods["k3lr-rx888"].samprate_hz, 64_800_000)

        self.assertEqual(coord.cpu.suite_cores, "0-11")
        self.assertEqual(coord.cpu.worker_cores, "2-11")
        self.assertTrue(coord.cpu.owns_timestd_affinity)

        hftimes = coord.instances_of("hf-timestd")
        self.assertEqual(len(hftimes), 2)
        self.assertEqual({h.instance for h in hftimes}, {"rx888-a", "airspy-b"})
        self.assertEqual(hftimes[0].extras.get("timing_authority"), "rtp")

        kaweb = coord.instances_of("ka9q-web")
        self.assertEqual(kaweb[0].extras.get("port"), 8081)

        bound_local = coord.instances_bound_to("k3lr-rx888")
        self.assertEqual({c.client_type for c in bound_local},
                         {"hf-timestd", "ka9q-web"})

    def test_load_from_disk(self):
        with tempfile.NamedTemporaryFile(mode='w', suffix='.toml', delete=False) as f:
            f.write(SAMPLE_TOML)
            path = Path(f.name)
        try:
            coord = load_coordination(path)
            self.assertEqual(coord.source_path, path)
            self.assertIn("k3lr-rx888", coord.radiods)
        finally:
            path.unlink()


class TestEnvKey(unittest.TestCase):

    def test_basic_upper(self):
        self.assertEqual(_env_key("RADIOD", "k3lr-rx888"), "RADIOD_K3LR_RX888")

    def test_collapses_underscores(self):
        self.assertEqual(_env_key("a", "", "b"), "A_B")

    def test_strips_non_alnum(self):
        self.assertEqual(_env_key("hf.timestd", "rx888/a"),
                         "HF_TIMESTD_RX888_A")


class TestRenderEnv(unittest.TestCase):

    def test_sample_rendering_contains_expected_keys(self):
        import tomllib
        coord = parse_coordination(tomllib.loads(SAMPLE_TOML))
        env = render_env(coord)

        self.assertIn("STATION_CALL=AI6VN", env)
        self.assertIn("STATION_GRID=CM88mc", env)
        self.assertIn("RADIOD_K3LR_RX888_HOST=localhost", env)
        self.assertIn("RADIOD_K3LR_RX888_STATUS=k3lr-rx888-status.local", env)
        self.assertIn("RADIOD_K3LR_RX888_SAMPRATE=64800000", env)
        self.assertIn("RADIOD_SHACK_AIRSPY_HOST=shack.local", env)
        self.assertIn("HF_TIMESTD_RX888_A_RADIOD=k3lr-rx888", env)
        self.assertIn("HF_TIMESTD_AIRSPY_B_RADIOD=shack-airspy", env)
        self.assertIn("KA9Q_WEB_K3LR_RX888_PORT=8081", env)

    def test_empty_coordination(self):
        env = render_env(Coordination())
        self.assertIn("Generated by sigmond", env)


class TestPassthroughExtras(unittest.TestCase):
    """The generic passthrough_extras mechanism replaces the legacy
    hardcoded ka9q-web port emission once clients opt in via deploy.toml.
    The legacy hardcode stays as a fallback for one release."""

    def _coord_with_extras(self, client_type: str, extras: dict):
        from sigmond.coordination import ClientInstance
        coord = Coordination()
        coord.clients = [ClientInstance(
            client_type=client_type, instance="default",
            radiod_id=None, extras=extras,
        )]
        return coord

    def test_generic_emission_uses_lookup(self):
        coord = self._coord_with_extras(
            "psk-recorder", {"port": 9090, "udp_ttl": 1})
        env = render_env(
            coord,
            passthrough_lookup=lambda ctype: ["port", "udp_ttl"]
                                              if ctype == "psk-recorder" else [],
        )
        self.assertIn("PSK_RECORDER_DEFAULT_PORT=9090", env)
        self.assertIn("PSK_RECORDER_DEFAULT_UDP_TTL=1", env)

    def test_lookup_returning_empty_skips_emission(self):
        coord = self._coord_with_extras("psk-recorder", {"port": 9090})
        env = render_env(coord, passthrough_lookup=lambda ctype: [])
        self.assertNotIn("PSK_RECORDER_DEFAULT_PORT", env)

    def test_unknown_keys_in_passthrough_list_are_skipped(self):
        coord = self._coord_with_extras("psk-recorder", {"port": 9090})
        env = render_env(
            coord,
            passthrough_lookup=lambda ctype: ["port", "absent_key"],
        )
        self.assertIn("PSK_RECORDER_DEFAULT_PORT=9090", env)
        self.assertNotIn("ABSENT_KEY", env)

    def test_legacy_ka9q_web_fallback_still_works(self):
        """When no deploy.toml lookup returns the key, the historical
        ka9q-web port emission still produces the same output the
        existing test suite asserts on."""
        import tomllib
        coord = parse_coordination(tomllib.loads(SAMPLE_TOML))
        env = render_env(coord, passthrough_lookup=lambda ctype: [])
        self.assertIn("KA9Q_WEB_K3LR_RX888_PORT=8081", env)

    def test_generic_path_does_not_double_emit_ka9q_web_port(self):
        """A ka9q-web instance whose deploy.toml lists 'port' must
        produce exactly one PORT line, not two."""
        import tomllib
        coord = parse_coordination(tomllib.loads(SAMPLE_TOML))
        env = render_env(
            coord,
            passthrough_lookup=lambda ctype: ["port"]
                                              if ctype == "ka9q-web" else [],
        )
        self.assertEqual(env.count("KA9Q_WEB_K3LR_RX888_PORT=8081"), 1)


class TestTimingAuthority(unittest.TestCase):
    """CLIENT-CONTRACT.md §18.3 — operator-declared timing-authority
    pointers, station-wide plus optional per-radiod overrides."""

    STATION_TOML = """\
[timing_authority]
source   = "hf-timestd@bee3"
endpoint = "unix:///run/hf-timestd/authority.sock"
tier_min = "T4"
"""

    PER_RADIOD_TOML = """\
[radiod."bee3-rx888"]
host        = "localhost"
status_dns  = "bee3-status.local"

[timing_authority]
source   = "hf-timestd@bee3"
endpoint = "unix:///run/hf-timestd/authority.sock"

[timing_authority.per_radiod."bee3-rx888"]
source   = "hf-timestd@bee3-special"
endpoint = "unix:///run/hf-timestd/special-authority.sock"
tier_min = "T5"
"""

    # Operator opened the [timing_authority] block but only filled in
    # `source` — endpoint missing.  The parsed object exists but
    # `is_declared` is False, so render_env emits nothing.  This is the
    # "half-configured" state a future validate-time warning would
    # surface; for now sigmond just silently skips emission rather
    # than emitting half a contract.
    INCOMPLETE_TOML = """\
[timing_authority]
source = "hf-timestd@bee3"
"""

    def test_dataclass_default_is_undeclared(self):
        ta = TimingAuthority()
        self.assertFalse(ta.is_declared)

    def test_dataclass_requires_both_source_and_endpoint(self):
        self.assertFalse(TimingAuthority(source="x").is_declared)
        self.assertFalse(TimingAuthority(endpoint="x").is_declared)
        self.assertTrue(TimingAuthority(source="x", endpoint="y").is_declared)

    def test_parse_station_wide(self):
        import tomllib
        coord = parse_coordination(tomllib.loads(self.STATION_TOML))
        self.assertEqual(coord.timing_authority.source, "hf-timestd@bee3")
        self.assertEqual(coord.timing_authority.endpoint,
                         "unix:///run/hf-timestd/authority.sock")
        self.assertEqual(coord.timing_authority.tier_min, "T4")
        self.assertTrue(coord.timing_authority.is_declared)
        self.assertEqual(coord.per_radiod_timing_authority, {})

    def test_parse_per_radiod(self):
        import tomllib
        coord = parse_coordination(tomllib.loads(self.PER_RADIOD_TOML))
        self.assertIn("bee3-rx888", coord.per_radiod_timing_authority)
        ta = coord.per_radiod_timing_authority["bee3-rx888"]
        self.assertEqual(ta.source, "hf-timestd@bee3-special")
        self.assertEqual(ta.endpoint,
                         "unix:///run/hf-timestd/special-authority.sock")
        self.assertEqual(ta.tier_min, "T5")
        self.assertTrue(ta.is_declared)

    def test_parse_absent_block_is_undeclared(self):
        """No [timing_authority] in coordination.toml → empty dataclass
        with is_declared False.  Backward-compat: any v0.6 coordination
        config loads cleanly on a v0.7 sigmond."""
        import tomllib
        coord = parse_coordination(tomllib.loads(SAMPLE_TOML))
        self.assertFalse(coord.timing_authority.is_declared)
        self.assertEqual(coord.per_radiod_timing_authority, {})

    def test_parse_incomplete_block_is_undeclared(self):
        """Operator declared the block but only filled in `source` →
        the dataclass exists but is_declared is False, so render_env
        will skip emission rather than emit half a contract."""
        import tomllib
        coord = parse_coordination(tomllib.loads(self.INCOMPLETE_TOML))
        self.assertEqual(coord.timing_authority.source, "hf-timestd@bee3")
        self.assertEqual(coord.timing_authority.endpoint, "")
        self.assertFalse(coord.timing_authority.is_declared)

    def test_render_emits_station_wide_keys(self):
        import tomllib
        coord = parse_coordination(tomllib.loads(self.STATION_TOML))
        env = render_env(coord)
        self.assertIn("TIMING_AUTHORITY=hf-timestd@bee3", env)
        self.assertIn(
            "TIMING_AUTHORITY_ENDPOINT=unix:///run/hf-timestd/authority.sock",
            env,
        )
        self.assertIn("TIMING_AUTHORITY_TIER_MIN=T4", env)

    def test_render_emits_per_radiod_keys(self):
        import tomllib
        coord = parse_coordination(tomllib.loads(self.PER_RADIOD_TOML))
        env = render_env(coord)
        self.assertIn(
            "RADIOD_BEE3_RX888_TIMING_AUTHORITY=hf-timestd@bee3-special",
            env,
        )
        self.assertIn(
            "RADIOD_BEE3_RX888_TIMING_AUTHORITY_ENDPOINT="
            "unix:///run/hf-timestd/special-authority.sock",
            env,
        )
        self.assertIn("RADIOD_BEE3_RX888_TIMING_AUTHORITY_TIER_MIN=T5", env)
        # Station-wide pointer also emitted alongside per-radiod, since
        # both scopes coexist in PER_RADIOD_TOML.
        self.assertIn("TIMING_AUTHORITY=hf-timestd@bee3", env)

    def test_render_omits_tier_min_when_unset(self):
        """tier_min is optional per §18.3 — when unset, the env key
        is not emitted, letting the client apply its own threshold."""
        import tomllib
        toml = self.STATION_TOML.replace('tier_min = "T4"\n', '')
        coord = parse_coordination(tomllib.loads(toml))
        env = render_env(coord)
        self.assertIn("TIMING_AUTHORITY=hf-timestd@bee3", env)
        self.assertNotIn("TIMING_AUTHORITY_TIER_MIN", env)

    def test_render_skips_undeclared_block(self):
        """No [timing_authority] in coordination.toml → no
        TIMING_AUTHORITY* keys in the rendered env.  Default mode."""
        import tomllib
        coord = parse_coordination(tomllib.loads(SAMPLE_TOML))
        env = render_env(coord)
        self.assertNotIn("TIMING_AUTHORITY=", env)
        self.assertNotIn("TIMING_AUTHORITY_ENDPOINT", env)
        self.assertNotIn("TIMING_AUTHORITY_TIER_MIN", env)

    def test_render_skips_incomplete_block(self):
        """Half-filled [timing_authority] (source but no endpoint) →
        no env keys.  No half-contracts."""
        import tomllib
        coord = parse_coordination(tomllib.loads(self.INCOMPLETE_TOML))
        env = render_env(coord)
        self.assertNotIn("TIMING_AUTHORITY=", env)
        self.assertNotIn("TIMING_AUTHORITY_ENDPOINT", env)

    def test_per_radiod_for_unknown_radiod_is_orphan(self):
        """If [timing_authority.per_radiod.<id>] names a radiod that
        isn't declared in [radiod.*], the per-radiod entry is parsed
        but its env keys never emit — render_env iterates radiods,
        not per_radiod_timing_authority keys, so an orphan entry is
        silently inert.  A future validate-time check could surface
        this as a warn-level issue."""
        toml = """\
[timing_authority]
source = "hf-timestd@bee3"
endpoint = "unix:///run/hf-timestd/authority.sock"

[timing_authority.per_radiod."nonexistent-radiod"]
source = "hf-timestd@phantom"
endpoint = "unix:///run/phantom.sock"
"""
        import tomllib
        coord = parse_coordination(tomllib.loads(toml))
        self.assertIn("nonexistent-radiod", coord.per_radiod_timing_authority)
        env = render_env(coord)
        self.assertNotIn("NONEXISTENT_RADIOD", env)
        self.assertNotIn("phantom", env)


if __name__ == "__main__":
    unittest.main()
