"""Tests for sigmond.coordination loader and env rendering."""

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'lib'))

from sigmond.coordination import (
    Coordination, load_coordination, parse_coordination, render_env, _env_key,
)


SAMPLE_TOML = """\
[host]
call = "AI6VN"
grid = "CM88mc"
lat  = 37.5
lon  = -122.25

[radiod."k3lr-rx888"]
host        = "localhost"
status_dns  = "k3lr-rx888-status.local"
samprate_hz = 64800000
cores       = "0-1"
radio_conf  = "/etc/radio/radiod@k3lr-rx888.conf"

[radiod."shack-airspy"]
host        = "shack.local"
status_dns  = "airspy-status.local"
samprate_hz = 10000000

[cpu]
suite_cores           = "0-11"
worker_cores          = "2-11"
owns_timestd_affinity = true

[[clients.hf-timestd]]
instance         = "rx888-a"
radiod_id        = "k3lr-rx888"
timing_authority = "rtp"

[[clients.hf-timestd]]
instance         = "airspy-b"
radiod_id        = "shack-airspy"
timing_authority = "auto"

[[clients.ka9q-web]]
instance  = "k3lr-rx888"
radiod_id = "k3lr-rx888"
port      = 8081

[disk_budget]
root_path    = "/var"
warn_percent = 80
"""


class TestLoadCoordination(unittest.TestCase):

    def test_empty_when_missing_file(self):
        path = Path('/tmp/does-not-exist-sigmond-coord.toml')
        if path.exists():
            path.unlink()
        coord = load_coordination(path)
        self.assertEqual(coord.host.call, "")
        self.assertEqual(coord.radiods, {})
        self.assertEqual(coord.clients, [])

    def test_parse_full_sample(self):
        import tomllib
        raw = tomllib.loads(SAMPLE_TOML)
        coord = parse_coordination(raw)

        self.assertEqual(coord.host.call, "AI6VN")
        self.assertEqual(coord.host.grid, "CM88mc")
        self.assertAlmostEqual(coord.host.lat, 37.5)

        self.assertIn("k3lr-rx888", coord.radiods)
        self.assertIn("shack-airspy", coord.radiods)
        self.assertTrue(coord.radiods["k3lr-rx888"].is_local)
        self.assertFalse(coord.radiods["shack-airspy"].is_local)
        self.assertEqual(coord.radiods["k3lr-rx888"].samprate_hz, 64_800_000)

        self.assertEqual(coord.cpu.suite_cores, "0-11")
        self.assertEqual(coord.cpu.worker_cores, "2-11")
        self.assertTrue(coord.cpu.owns_timestd_affinity)

        hftimes = coord.instances_of("hf-timestd")
        self.assertEqual(len(hftimes), 2)
        self.assertEqual({h.instance for h in hftimes}, {"rx888-a", "airspy-b"})
        self.assertEqual(hftimes[0].extras.get("timing_authority"), "rtp")

        kaweb = coord.instances_of("ka9q-web")
        self.assertEqual(kaweb[0].extras.get("port"), 8081)

        bound_local = coord.instances_bound_to("k3lr-rx888")
        self.assertEqual({c.client_type for c in bound_local},
                         {"hf-timestd", "ka9q-web"})

    def test_load_from_disk(self):
        with tempfile.NamedTemporaryFile(mode='w', suffix='.toml', delete=False) as f:
            f.write(SAMPLE_TOML)
            path = Path(f.name)
        try:
            coord = load_coordination(path)
            self.assertEqual(coord.source_path, path)
            self.assertIn("k3lr-rx888", coord.radiods)
        finally:
            path.unlink()


class TestEnvKey(unittest.TestCase):

    def test_basic_upper(self):
        self.assertEqual(_env_key("RADIOD", "k3lr-rx888"), "RADIOD_K3LR_RX888")

    def test_collapses_underscores(self):
        self.assertEqual(_env_key("a", "", "b"), "A_B")

    def test_strips_non_alnum(self):
        self.assertEqual(_env_key("hf.timestd", "rx888/a"),
                         "HF_TIMESTD_RX888_A")


class TestRenderEnv(unittest.TestCase):

    def test_sample_rendering_contains_expected_keys(self):
        import tomllib
        coord = parse_coordination(tomllib.loads(SAMPLE_TOML))
        env = render_env(coord)

        self.assertIn("STATION_CALL=AI6VN", env)
        self.assertIn("STATION_GRID=CM88mc", env)
        self.assertIn("RADIOD_K3LR_RX888_HOST=localhost", env)
        self.assertIn("RADIOD_K3LR_RX888_STATUS=k3lr-rx888-status.local", env)
        self.assertIn("RADIOD_K3LR_RX888_SAMPRATE=64800000", env)
        self.assertIn("RADIOD_SHACK_AIRSPY_HOST=shack.local", env)
        self.assertIn("HF_TIMESTD_RX888_A_RADIOD=k3lr-rx888", env)
        self.assertIn("HF_TIMESTD_AIRSPY_B_RADIOD=shack-airspy", env)
        self.assertIn("KA9Q_WEB_K3LR_RX888_PORT=8081", env)

    def test_empty_coordination(self):
        env = render_env(Coordination())
        self.assertIn("Generated by sigmond", env)


if __name__ == "__main__":
    unittest.main()
